"""Build the results-explanation .docx for the Llama-3-8B run.

Numbers are the 300-split headline / score-ablation on results/graded_claims.jsonl.
Run:  python figures/make_docx.py
"""
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

ACCENT = RGBColor(0x1F, 0x4E, 0x79)
doc = Document()

# ---- base styles ----
normal = doc.styles["Normal"]
normal.font.name = "Calibri"
normal.font.size = Pt(11)
doc.styles["Normal"].paragraph_format.space_after = Pt(6)


def heading(text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = ACCENT
    return h


def para(text, bold=False, italic=False, size=None):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold, r.italic = bold, italic
    if size:
        r.font.size = Pt(size)
    return p


def bullet(text_runs):
    """text_runs: list of (text, bold) tuples on one bullet line."""
    p = doc.add_paragraph(style="List Bullet")
    for t, b in text_runs:
        r = p.add_run(t)
        r.bold = b
    return p


def table(headers, rows, widths=None):
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Light Grid Accent 1"
    for i, h in enumerate(headers):
        c = t.rows[0].cells[i]
        c.text = ""
        run = c.paragraphs[0].add_run(h)
        run.bold = True
    for row in rows:
        cells = t.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = ""
            cells[i].paragraphs[0].add_run(str(val))
    if widths:
        for col, w in enumerate(widths):
            for row in t.rows:
                row.cells[col].width = Inches(w)
    doc.add_paragraph()
    return t


# ============================================================ TITLE
title = doc.add_heading("Severity-Aware Conformal Risk Control for Medical LLM Hallucinations", level=0)
for run in title.runs:
    run.font.color.rgb = ACCENT
sub = para("Results & Interpretation — Llama-3-8B-Instruct on the K-QA clinical benchmark", italic=True)
sub.alignment = WD_ALIGN_PARAGRAPH.LEFT
para("This note explains what our experiments found and what each number means, using concrete "
     "examples throughout. Every figure below is computed over 300 random calibration/test splits of "
     "2,150 verifiable claims generated by Llama-3-8B and graded by a GPT-4o judge.")

# ============================================================ 1. DATA
heading("1. The data we generated", 1)
para("We had Llama-3-8B answer 201 real clinical questions, split each answer into atomic claims, and "
     "had the judge decide (a) whether each claim is true or a hallucination, and (b) how harmful it "
     "would be if it were wrong. This produced 5,040 claims:")

table(
    ["Category", "Count", "What it means (with an example)"],
    [
        ["True", "1,819", "Supported by the physician answer. E.g. “Ibuprofen is a nonsteroidal anti-inflammatory drug.”"],
        ["Hallucination", "331", "Contradicted by the answer. E.g. “Ibuprofen is safe throughout pregnancy” (it is not)."],
        ["Unverifiable", "2,890", "The answer neither confirms nor denies it, so it cannot be graded — set aside."],
        ["Verifiable (used)", "2,150", "True + hallucination. All calibration and measurement happen here."],
    ],
    widths=[1.4, 0.8, 4.3],
)

para("Each verifiable claim is also tagged by severity:")
table(
    ["Severity tier", "Claims", "Baseline hallucination rate", "Example of a claim in this tier"],
    [
        ["Dangerous", "468", "13.2%", "“Take 4 g of acetaminophen every 4 hours” — a dosing error can harm a patient."],
        ["Benign", "1,682", "16.0%", "“Acetaminophen is metabolized in the liver” — low harm if wrong."],
    ],
    widths=[1.2, 0.7, 1.7, 3.2],
)
para("Anchor this number: before any filtering, about 13 of every 100 dangerous claims the model "
     "produces are hallucinations. Our safety target is to bring that down to 5 in 100.", bold=False)

# ============================================================ 2. HOW TO READ
heading("2. How to read the numbers", 1)
para("Four quantities appear throughout. Each is easiest to understand through an example.")

para("Risk", bold=True)
para("Among the claims we decide to keep (show to the clinician), the fraction that are hallucinations. "
     "Lower is safer. Example: if we keep 200 dangerous claims and 9 of them are wrong, the risk is "
     "9/200 = 0.045. A budget of 0.05 is the promise “no more than 5 wrong per 100 shown.”")

para("Retention", bold=True)
para("Among the claims that are actually true, the fraction we keep. Higher is more useful. Example: "
     "there are 100 true dangerous claims; if the system shows 84 and withholds 16 (because it wasn’t "
     "confident enough), retention is 0.84. A withheld true claim does no harm — it is just a missed "
     "opportunity to be helpful. (Note the tension: you could force risk to zero by keeping nothing, but "
     "then retention is zero and the system is useless. The goal is to meet the risk budget while keeping "
     "retention high.)")

para("Violation rate", bold=True)
para("We repeat the entire calibrate-then-test procedure 300 times on different random splits of the "
     "data. The violation rate is the fraction of those runs in which the dangerous risk ended up above "
     "the 0.05 budget. Example: if 84 of 300 runs exceed 0.05, the violation rate is 0.28. This tells us "
     "how reliably the promise holds — not just whether it holds on average.")

para("AUROC (score quality)", bold=True)
para("How well the confidence score separates true claims from hallucinations. 1.0 is perfect, 0.5 is a "
     "coin flip. Concretely, our 0.87 means: pick one true claim and one hallucination at random; 87% of "
     "the time the model assigns the true one a higher confidence. This is the raw material the filtering "
     "works with.")

# ============================================================ 3. MAIN RESULT
heading("3. The main result", 1)
para("We compare two ways of choosing the keep/drop threshold:")
bullet([("Global — ", True), ("one threshold for every claim, tuned so overall hallucinations sit near 10%.", False)])
bullet([("Severity-aware (ours) — ", True), ("separate thresholds: dangerous claims held to ≤5% error, benign allowed up to ≤15%.", False)])

para("How to read the “Global” column. ", bold=True)
para("The global method uses only one threshold for every claim. The separate dangerous and benign "
     "numbers in its column are therefore not two targets — they are what we measure in each tier after "
     "applying that single shared threshold. Picture one gate that every claim must clear; we then go back "
     "and count the leftover hallucination rate among the dangerous claims that got through (0.100) and "
     "among the benign ones (0.095). Both land near 10% precisely because one threshold cannot aim at two "
     "budgets — which is exactly why the dangerous tier stays stuck at twice the 5% we want. Severity-aware "
     "control, by contrast, uses a separate threshold per tier, so each tier’s risk is actually controlled "
     "rather than merely measured.")

para("On the dangerous tier:", bold=True)
table(
    ["Metric (dangerous tier)", "Global", "Severity-aware", "Budget"],
    [
        ["Hallucination risk", "0.100", "0.046", "≤ 0.05"],
        ["Budget violated (of 300 splits)", "99.7%", "28%", "—"],
        ["True claims kept (retention)", "0.968", "0.837", "—"],
    ],
    widths=[2.7, 1.2, 1.5, 1.0],
)
doc.add_picture("figures/fig_main_dangerous.png", width=Inches(6.3))
doc.add_paragraph()

para("What this means, walked through with 1,000 kept dangerous claims:", bold=True)
bullet([("Global lets about 100 hallucinations through", True),
        (" — double the 5% we promised. And it is not a one-off: across 300 re-runs it broke the 5% "
         "promise on 299 of them. It looks acceptable on the overall average only because benign claims "
         "vastly outnumber dangerous ones, so the dangerous failures are hidden inside the global average.", False)])
bullet([("Severity-aware lets about 46 through", True),
        (" — inside the budget — and stays inside far more reliably (it exceeded 0.05 on only ~84 of 300 runs).", False)])
bullet([("The cost is honest and modest:", True),
        (" of every 100 true dangerous claims we now surface 84 instead of 97. We withhold roughly 13 "
         "extra correct claims per 100 to buy that safety — and those withheld claims cause no harm, they "
         "are simply not shown.", False)])
para("In one line: severity-aware control roughly halves the dangerous error rate (0.100 → 0.046) and "
     "the only price is withholding a modest slice of true dangerous claims.")

# ============================================================ 4. BENIGN
heading("4. The benign side — a reallocation, not just “stricter”", 1)
table(
    ["Metric (benign tier)", "Global", "Severity-aware", "Budget"],
    [
        ["Hallucination risk", "0.095", "0.148", "≤ 0.15"],
        ["True claims kept (retention)", "0.950", "0.998", "—"],
    ],
    widths=[2.7, 1.2, 1.5, 1.0],
)
para("Severity-aware control is not uniformly stricter. On benign claims — where a mistake is cheap — it "
     "deliberately relaxes, allowing up to 15% error, which lets it keep almost every true benign claim "
     "(99.8%, up from 95%). So the system shifts caution toward where harm is high and eases off where "
     "harm is low. The net effect is better protection on dangerous claims and more true benign claims "
     "kept at the same time. Example: a slightly-off historical detail is allowed through so that the "
     "many correct background facts are not needlessly withheld, while every dosing claim is scrutinized "
     "hard.")

# ============================================================ 5. ABLATION
heading("5. Does the result depend on the confidence score?", 1)
para("We re-ran the whole comparison while swapping the confidence score, including a Random "
     "(coin-flip) score as a sanity floor. The two columns below are the severity-aware dangerous-tier "
     "risk and retention.")
table(
    ["Confidence score", "AUROC", "Dangerous risk (ours)", "Dangerous retention"],
    [
        ["P(true) — model self-confidence", "0.868", "0.046", "0.837"],
        ["NLI entailment vs. answer", "0.705", "0.047", "0.384"],
        ["Sequence log-probability", "0.593", "0.047", "0.257"],
        ["Random (noise floor)", "0.511", "0.047", "0.408"],
    ],
    widths=[2.8, 0.9, 1.7, 1.5],
)
doc.add_picture("figures/fig_ablation.png", width=Inches(6.3))
doc.add_paragraph()

para("Two takeaways:", bold=True)
bullet([("Safety is guaranteed by the method, not by a good score.", True),
        (" Every score — even pure coin-flip noise — keeps the dangerous risk within the 0.05 budget. "
         "Even if we ranked claims at random, the dangerous error rate stays ≤5%.", False)])
bullet([("Usefulness is what the score buys.", True),
        (" With the model’s real confidence we keep 84% of true dangerous claims; with coin-flip noise "
         "only ~41% — technically safe but useless, because to stay safe with a meaningless score you must "
         "throw away most claims. The model’s own confidence (AUROC 0.87) is a strong score, which is why "
         "it retains so much.", False)])
para("Honest caveat: among the weak scores the retention numbers are close and a little noisy, because "
     "the dangerous tier is small (468 claims) — so the small differences there should not be over-read. "
     "The robust signal is that the strong score retains far more than the weak ones.", italic=True)

# ============================================================ 6. LIMITATIONS
heading("6. Limitations", 1)
bullet([("Severity tags are the GPT-4o judge’s decision, not yet validated by clinicians — our next priority.", False)])
bullet([("The dangerous tier is small (468 verifiable claims), so its numbers carry more uncertainty; we will add confidence intervals.", False)])
bullet([("The 0.05 guarantee is on the average across splits, so individual runs can exceed it — which is why the violation rate is not zero.", False)])
bullet([("These are results for one model on one dataset; a second model (Mistral-7B) is running now.", False)])

# ============================================================ 7. BOTTOM LINE
heading("7. Bottom line", 1)
para("On real clinical questions with Llama-3-8B, a single global filter quietly lets dangerous medical "
     "claims through at twice the intended error rate. Making the filter severity-aware cuts that "
     "dangerous error rate roughly in half — back within budget — while still surfacing 84% of true "
     "dangerous claims and nearly all true benign ones. And because the safety comes from the method "
     "rather than the score, the guarantee is robust: it held for every confidence score we tried, even "
     "random noise.")

out = "results_summary_llama3-8b.docx"
doc.save(out)
print("wrote", out)
